### ISSUE TITLE
doppkit improvements

### ISSUE THREAD

**Issue by msmitherdc** [hobuinc/doppkit#8]
- [ ] for large transfers, it builds the list and then starts the transfer, for short duration presigned urls, this is a problem in that the url is retrieved but not downloaded until much later and it times out - depth first not depth first

**Comment by hobu** [comment]
> it builds the list and then starts the transfer, 

Instead of trapping, we should wait to fire the HEAD/GET request until we are actually going to fetch it. As async code, it should be able to build the list *as* it starts transferring. The distinction doesn't matter until the list gets so big.

**Comment by j9ac9k** [comment]
Fixed with #10
